### PR TITLE
enabled choice_translation_domain for symfony 2.7+

### PR DESCRIPTION
**Pull request by virtualize**

### CODE REVIEW

**Comment by pkraeutli** [comment]
Does this also work with Symfony < 2.7? If not, composer.json needs to be updated I think.

**Comment by virtualize** [comment]
No this won't work with < 2.7. Would propose 0.4 release

**Comment by matejvelikonja** [comment]
or make an if statement and check if it's version 2.7 or lower.

**Comment by virtualize** [comment]
as you wish: https://github.com/astina/AstinaLabelsBundle/pull/5

**Pull request closed without merging**
